add delete method, so that box wouldnt stack with junk mails
fhoeben/hsac-fitnesse-email pull request #4
Opened 2019-11-05 11:30 UTC by Taxanas

2019-11-05 14:52 UTC, fhoeben requested changes
Seems like a good feature. I always expected to move messages to 'Trash' mailbox.

Some comments/questions though...

2019-11-05 14:52 UTC, fhoeben commented on src/main/java/nl/hsac/fitnesse/fixture/slim/EmailFixture.java
> +                throw new StopTestException("failed to mark as deleted: " + e);
Other methods throw SlimFixtureException, why did you choose StopTest here?
Please use overload with accepts cause as 2nd parameter instead just appending String version of exception.

2019-11-05 14:52 UTC, fhoeben commented on src/main/java/nl/hsac/fitnesse/fixture/slim/EmailFixture.java
> +    public void markAsDeleted() {
Would `markLastMessageAsDeleted` not be a better name (in line with `moveLastMessageToFolder`)?

2019-11-05 14:52 UTC, fhoeben commented on src/main/java/nl/hsac/fitnesse/fixture/slim/EmailFixture.java
> +        if (lastMessage != null) {
Should an exception be thrown if there is no last message? I.e. `throw new SlimFixtureException(false, "There is no last message to mark as deleted");`

2019-11-07 15:41 UTC, Taxanas commented on src/main/java/nl/hsac/fitnesse/fixture/slim/EmailFixture.java
> +    public void markAsDeleted() {
Sure, will do ;)

2019-11-07 15:43 UTC, Taxanas commented on src/main/java/nl/hsac/fitnesse/fixture/slim/EmailFixture.java
> +        if (lastMessage != null) {
You are right ;)

2019-11-07 15:43 UTC, Taxanas commented on src/main/java/nl/hsac/fitnesse/fixture/slim/EmailFixture.java
> +                throw new StopTestException("failed to mark as deleted: " + e);
Will try :)

2019-11-07 16:04 UTC, Taxanas reviewed
Changes done

2019-11-08 07:19 UTC, merged